app1/urls.py
from django.urls import path
from app1.views import *

app_name='app1'

urlpatterns=[
    path('vruta/',vruta,name='vruta'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='app2'

urlpatterns=[
    path('ruvee/',ruvee,name='ruvee'),
]

project16/urls.py
from django.contrib import admin
from django.urls import path,include
from app3.views import *
import app1
import app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('task/',task,name='task'),
    
]

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def vruta(request):
    return render(request,'vruta.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def ruvee(request):
    return render(request,'ruvee.html')

app3/views.py
from django.shortcuts import render

# Create your views here.
def task(request):
    return render(request,'task.html')

templates/ruvee.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Hey Good morning </h1>
        <h1>Today we discuss about specific url navigation</h1>

    <h1><a href="{% url 'app1:vruta' %}">click here and go to vruta page</a></h1>
    </center>
    
</body>
</html>

templates/task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is task page</h1>

    <h1><a href="{% url 'app1:vruta' %}">click here and go vruta page</a></h1>
    </center>

</body>
</html>

templates/vruta.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Hello my name is Vruta</h1>
        <h1>Today we discuss about url navigation</h1>
    <h1><a href="{% url 'app2:ruvee' %}">click here and go to ruvee page</a></h1>
    </center>
</body>
</html>